-- Support ticket emails.
--
-- These slugs have always been sent but never seeded, so every ticket
-- acknowledgement, reply and status change went out as an empty message
-- titled "Notification". A template a shopkeeper has edited is left alone.

INSERT INTO wk_email_templates (slug, name, subject, body, is_active) VALUES

('ticket-created', 'Support Ticket Received', 'We have your message — ticket {{ticket_number}}',
'<div style="text-align:center;margin-bottom:28px"><div style="font-size:52px;margin-bottom:8px">&#127915;</div><h1 style="font-size:27px;font-weight:900;margin:0 0 6px;color:#1e1b2e">We have your message</h1><p style="color:#6b7280;margin:0;font-size:15px">Ticket {{ticket_number}}</p></div><p style="font-size:15px;line-height:1.7;margin:0 0 20px">Hello {{customer_name}}, thank you for getting in touch. We have opened a ticket and will reply as soon as we can.</p><div style="background:#faf8f6;border-radius:10px;padding:18px 20px;margin-bottom:24px"><div style="font-size:11px;font-weight:800;text-transform:uppercase;letter-spacing:1px;color:#6b7280;margin-bottom:5px">Subject</div><div style="font-size:15px;font-weight:700">{{ticket_subject}}</div></div><div style="text-align:center"><a href="{{store_url}}" style="display:inline-block;background:linear-gradient(135deg,#8b5cf6,#ec4899);color:#fff;padding:14px 32px;border-radius:10px;text-decoration:none;font-weight:800;font-size:15px">Visit {{store_name}}</a></div>', 1),

('ticket-reply', 'Support Ticket Reply', 'Re: {{ticket_subject}} — ticket {{ticket_number}}',
'<div style="text-align:center;margin-bottom:28px"><div style="font-size:52px;margin-bottom:8px">&#128172;</div><h1 style="font-size:27px;font-weight:900;margin:0 0 6px;color:#1e1b2e">We have replied</h1><p style="color:#6b7280;margin:0;font-size:15px">Ticket {{ticket_number}} &middot; {{ticket_subject}}</p></div><div style="background:#ede9fe;border-left:3px solid #8b5cf6;border-radius:0 10px 10px 0;padding:20px;margin-bottom:24px"><div style="font-size:11px;font-weight:800;text-transform:uppercase;letter-spacing:1px;color:#8b5cf6;margin-bottom:6px">{{agent_name}} wrote</div><div style="font-size:14px;line-height:1.7">{{reply_message}}</div></div><p style="font-size:14px;line-height:1.7;color:#6b7280;margin:0 0 22px">Hello {{customer_name}}, if that does not settle it, reply on the ticket and we will pick it up.</p><div style="text-align:center"><a href="{{ticket_url}}" style="display:inline-block;background:linear-gradient(135deg,#8b5cf6,#ec4899);color:#fff;padding:14px 32px;border-radius:10px;text-decoration:none;font-weight:800;font-size:15px">Open the ticket</a></div>', 1),

('ticket-status-update', 'Support Ticket Status', 'Ticket {{ticket_number}} is now {{ticket_status}}',
'<div style="text-align:center;margin-bottom:28px"><div style="font-size:52px;margin-bottom:8px">&#127915;</div><h1 style="font-size:27px;font-weight:900;margin:0 0 6px;color:#1e1b2e">Your ticket is now {{ticket_status}}</h1><p style="color:#6b7280;margin:0;font-size:15px">Ticket {{ticket_number}}</p></div><div style="background:#faf8f6;border-radius:10px;padding:18px 20px;margin-bottom:24px"><div style="font-size:11px;font-weight:800;text-transform:uppercase;letter-spacing:1px;color:#6b7280;margin-bottom:5px">Subject</div><div style="font-size:15px;font-weight:700">{{ticket_subject}}</div></div><p style="font-size:14px;line-height:1.7;color:#6b7280;margin:0 0 22px">Hello {{customer_name}}, if there is more to say, reply on the ticket and it will reopen.</p><div style="text-align:center"><a href="{{store_url}}" style="display:inline-block;background:linear-gradient(135deg,#8b5cf6,#ec4899);color:#fff;padding:14px 32px;border-radius:10px;text-decoration:none;font-weight:800;font-size:15px">Visit {{store_name}}</a></div>', 1)

ON DUPLICATE KEY UPDATE slug = slug;
