<?php
/**
 * WHISKER — Application Configuration
 *
 * The installer generates this file. To set up manually, copy this to
 * config.php and edit the values.
 *
 * Note: the running version is NOT tracked in this file. See
 * `app/version.php` for the single source of truth shipped with each
 * release. Don't add a 'version' key here — the front controller no
 * longer reads it (config.php from older installs that still have one
 * will continue to work as a fallback).
 */

return [
    'app_name'    => 'Whisker',
    'base_url'    => 'http://localhost/whisker',   // No trailing slash
    'base_path'   => '/whisker',                    // URL path prefix (use '/' if at domain root)
    'debug'       => false,
    'timezone'    => 'Asia/Kolkata',
    // 'salt' is generated by the installer; preserve it across updates.
];
